from .generate_screen_desc import generate_screen_desc_tmpl
from .generate_element_content_desc import generate_element_content_desc_tmpl
from .generate_flow_desc import generate_flow_desc_tmpl
from .query_similar_flows import query_similar_flows_tmpl
from .identify_app import identify_app_tmpl
from .identifying_next_memory_generate_action import identifying_next_memory_generate_action_tmpl

from .identifying_next_execute_action import identifying_next_execute_action_tmpl
from .identifying_next_execute_action import identifying_next_execute_action_with_only_user_guide_tmpl
from .identifying_next_execute_action import identifying_next_execute_action_with_only_similar_flow_tmpl
from .identifying_next_execute_action import indentifying_next_execute_action_with_only_current_screen_tmpl


